/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SudokuSolverJNI */

#ifndef SudokuSolverJNI
#define SudokuSolverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_birgitkratz_sudokusolver_jni_SudokuSolverJNI
 * Method:    solveSudoku
 * Signature: ([[I)[I
 */
JNIEXPORT jintArray JNICALL Java_de_birgitkratz_sudokusolver_jni_SudokuSolverJNI_solveSudoku
        (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
